# Configuration Nixpacks pour le Frontend Flutter DONS
[phases.setup]
nixPkgs = ["nodejs", "npm", "python3"]

[phases.install]
cmds = [
    "npm install -g @flutter/cli",
    "flutter pub get"
]

[phases.build]
cmds = [
    "flutter build web --release"
]

[start]
cmd = "cd build/web && python3 -m http.server 3000"