[phases.setup]
nixPkgs = ["flutter", "python3"]

[phases.install]
cmds = [
  "cd . && flutter config --no-analytics",
  "cd . && cp pubspec-simple.yaml pubspec.yaml",
  "cd . && flutter pub get"
]

[phases.build]
cmds = [
  "cd . && flutter build web --release --web-renderer html",
  "cd . && chmod +x setup-complete.sh && ./setup-complete.sh"
]

[start]
cmd = "cd build/web && python3 static-server.py"
