name: frontend
description: "Application de gestion de cotisations pour groupes et associations"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  dio: ^5.4.0
  provider: ^6.1.1
  fl_chart: ^0.66.2
  shared_preferences: ^2.2.2
  go_router: ^13.2.5
  flutter_svg: ^2.0.13
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
