version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/backend/database/database.sqlite
    volumes:
      - ./backend/database:/var/www/html/backend/database
      - ./backend/storage:/var/www/html/backend/storage
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: dons_db
      MYSQL_USER: dons_user
      MYSQL_PASSWORD: dons_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: dons_user
      PMA_PASSWORD: dons_password
    ports:
      - "8080:80"
    depends_on:
      - db

volumes:
  mysql_data:
