version: '3.8'

services:
  dons-app:
    build: .
    ports:
      - "80:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=pgsql
      - DB_HOST=dons-database
      - DB_PORT=5432
      - DB_DATABASE=Dons
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_KEY=${APP_KEY}
      - APP_URL=${APP_URL:-http://localhost}
    volumes:
      - ./backend/storage:/var/www/html/backend/storage
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - dons-database

  dons-database:
    image: postgres:15
    environment:
      POSTGRES_DB: Dons
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dons_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d Dons"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  dons_data:
