[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nginx"]

[phases.install]
cmds = [
  "cd backend && composer install --ignore-platform-reqs --no-dev --optimize-autoloader"
]

[phases.build]
cmds = []

[start]
cmd = "cd backend && php-fpm -y /assets/php-fpm.conf & nginx -c /nginx.conf"
