[phases.setup]
nixPkgs = ["flutter", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
  "cd frontend && flutter pub get",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && flutter build web --release --web-renderer html",
  "mkdir -p /app/frontend-deploy",
  "cp -r /app/frontend/build/web/* /app/frontend-deploy/",
  "cp /app/frontend/static-server.py /app/frontend-deploy/"
]

[start]
cmd = "cd /app/frontend-deploy && python3 static-server.py"
