[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = [
  "echo 'Installation des dépendances Python...'"
]

[phases.build]
cmds = [
  "cd frontend && chmod +x setup-complete.sh && ./setup-complete.sh"
]

[start]
cmd = "cd frontend && python3 static-server.py"
