[phases.setup]
nixPkgs = ["python3"]

[phases.install]
cmds = [
  "echo 'Installation des dépendances Python...'"
]

[phases.build]
cmds = [
  "mkdir -p build/web",
  "cat > build/web/index.html << 'EOF'",
  "<!DOCTYPE html>",
  "<html>",
  "<head>",
  "    <title>DONS - Système de gestion de cotisations</title>",
  "    <meta charset=\"utf-8\">",
  "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">",
  "    <style>",
  "        body { font-family: Arial, sans-serif; margin: 40px; background: #f5f5f5; }",
  "        .container { max-width: 800px; margin: 0 auto; background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }",
  "        .header { text-align: center; color: #2c3e50; margin-bottom: 30px; }",
  "        .content { margin: 20px 0; }",
  "        .api-link { display: inline-block; margin: 10px; padding: 15px 25px; background: #3498db; color: white; text-decoration: none; border-radius: 5px; transition: background 0.3s; }",
  "        .api-link:hover { background: #2980b9; }",
  "        .feature { margin: 15px 0; padding: 15px; background: #f8f9fa; border-left: 4px solid #3498db; }",
  "        .status { color: #27ae60; font-weight: bold; }",
  "    </style>",
  "</head>",
  "<body>",
  "    <div class=\"container\">",
  "        <h1 class=\"header\">🚀 DONS - Système de gestion de cotisations</h1>",
  "        <div class=\"content\">",
  "            <p class=\"status\">✅ Frontend déployé avec succès !</p>",
  "            <p>Bienvenue dans l'application DONS ! Cette interface vous permet de gérer les cotisations pour vos groupes et associations.</p>",
  "",
  "            <h2>🔗 Liens utiles :</h2>",
  "            <a href=\"/api\" class=\"api-link\">API Backend</a>",
  "            <a href=\"/api/test\" class=\"api-link\">Test API</a>",
  "            <a href=\"/api/campaign\" class=\"api-link\">Campaign API</a>",
  "            <a href=\"/api/payments\" class=\"api-link\">Payments API</a>",
  "",
  "            <h2>📋 Fonctionnalités :</h2>",
  "            <div class=\"feature\">",
  "                <strong>Gestion des groupes</strong> - Créez et gérez vos groupes d'associations",
  "            </div>",
  "            <div class=\"feature\">",
  "                <strong>Suivi des cotisations</strong> - Suivez les paiements et contributions",
  "            </div>",
  "            <div class=\"feature\">",
  "                <strong>Paiements sécurisés</strong> - Intégration avec BPay pour les paiements",
  "            </div>",
  "            <div class=\"feature\">",
  "                <strong>Tableau de bord administrateur</strong> - Interface complète de gestion",
  "            </div>",
  "",
  "            <h2>🔧 Configuration :</h2>",
  "            <p>Backend Laravel : <strong>adm.pront-ix.com</strong></p>",
  "            <p>Base de données : <strong>PostgreSQL</strong></p>",
  "            <p>Frontend : <strong>HTML statique</strong></p>",
  "        </div>",
  "    </div>",
  "</body>",
  "</html>",
  "EOF"
]

[start]
cmd = "cd build/web && python3 -m http.server 80"
